//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingPurpose
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookingPurpose()
        {
            this.Booking = new HashSet<Booking>();
        }
    
        public int ID { get; set; }
        public System.DateTime Modified { get; set; }
        public string NACode { get; set; }
        public string Title { get; set; }
        public System.DateTime dbedited { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Booking { get; set; }
    }
}
