//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetails
    {
        public int ID { get; set; }
        public Nullable<bool> Guest { get; set; }
        public string TravelDocumentName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> CheckinDate { get; set; }
        public Nullable<System.DateTime> CheckoutDate { get; set; }
        public string TravelType { get; set; }
        public string OfficeEmail { get; set; }
        public Nullable<int> OfficeNameId { get; set; }
        public string OfficeNameText { get; set; }
        public Nullable<int> ReferenceNumberId { get; set; }
        public Nullable<int> CostCenterCodeId { get; set; }
        public Nullable<int> FactoryCodeId { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> DetailFactoryCodeId { get; set; }
        public string StaffTitle { get; set; }
        public Nullable<bool> CancelFlag { get; set; }
        public string CancelSettled { get; set; }
        public Nullable<System.DateTime> ActualCheckinDate { get; set; }
        public Nullable<System.DateTime> ActualCheckoutDate { get; set; }
        public Nullable<byte> NumberOfRoomNights { get; set; }
        public Nullable<int> SubFactoryId { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<int> ChargeTypeId { get; set; }
        public Nullable<decimal> ChargeValue { get; set; }
        public bool ChargedCancel { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public System.DateTime dbedited { get; set; }
        public bool IsDorm { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Remarks { get; set; }
        public string StaffDepartment { get; set; }
        public string Title { get; set; }
        public bool Alloc_x0020_Flag { get; set; }
    }
}
