//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.DormAllocation = new HashSet<DormAllocation>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string RequestorFactoryCode { get; set; }
        public string RequestorDepartmentCode { get; set; }
        public string RequestorName { get; set; }
        public System.DateTime CheckinDate { get; set; }
        public System.DateTime CheckoutDate { get; set; }
        public string Status { get; set; }
        public string AllGuestName { get; set; }
        public string StatusForDetailsUsed { get; set; }
        public Nullable<System.DateTime> dbedited { get; set; }
        public string AdminRemarks { get; set; }
        public int AuthorId { get; set; }
        public int BookingPurposeCodeId { get; set; }
        public Nullable<System.DateTime> ChargeValueCalculatedDate { get; set; }
        public Nullable<int> EditorId { get; set; }
        public int FactoryCodeId { get; set; }
        public bool IsUpdate { get; set; }
        public System.DateTime Modified { get; set; }
        public int NumberOfRooms { get; set; }
        public string Remarks { get; set; }
        public string StaffEmails { get; set; }
        public Nullable<bool> StaffGrade { get; set; }
        public Nullable<bool> IsDorm { get; set; }
    
        public virtual BookingPurpose BookingPurpose { get; set; }
        public virtual Factory Factory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DormAllocation> DormAllocation { get; set; }
    }
}
