//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCenter
    {
        public int ID { get; set; }
        public string DepartmentCode { get; set; }
        public string DepartmentCode_x002d_CH { get; set; }
        public int EditorId { get; set; }
        public int FactoryCodeId { get; set; }
        public System.DateTime Modified { get; set; }
        public string SubFactory { get; set; }
        public string Title { get; set; }
        public System.DateTime dbedited { get; set; }
    }
}
