//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DormMemo
    {
        public System.DateTime Date { get; set; }
        public int DormNumerId { get; set; }
        public string Title { get; set; }
        public string link { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public int userid { get; set; }
    }
}
