//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HotelDataTestEntities : DbContext
    {
        public HotelDataTestEntities()
            : base("name=HotelDataTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookingPurpose> BookingPurpose { get; set; }
        public virtual DbSet<CostCenter> CostCenter { get; set; }
        public virtual DbSet<Factory> Factory { get; set; }
        public virtual DbSet<maintenancing> maintenancing { get; set; }
        public virtual DbSet<MyList> MyList { get; set; }
        public virtual DbSet<FactoryCode> FactoryCode { get; set; }
        public virtual DbSet<Dorm> Dorm { get; set; }
        public virtual DbSet<Booking> Booking { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<BookingDetails> BookingDetails { get; set; }
        public virtual DbSet<Hotel> Hotel { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<DormRoomStatus> DormRoomStatus { get; set; }
        public virtual DbSet<DormInDates> DormInDates { get; set; }
        public virtual DbSet<DormMemo> DormMemo { get; set; }
        public virtual DbSet<StatisticsByDay> StatisticsByDay { get; set; }
        public virtual DbSet<DormAllocation> DormAllocation { get; set; }
    
        public virtual int StatisticData(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StatisticData", startDateParameter, endDateParameter);
        }
    }
}
