//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DormInDates
    {
        public System.DateTime Date { get; set; }
        public int DAID { get; set; }
        public int DormNumerId { get; set; }
        public Nullable<System.DateTime> dbedited { get; set; }
        public int DormCodeID { get; set; }
    
        public virtual DormInDates DormInDates1 { get; set; }
        public virtual DormInDates DormInDates2 { get; set; }
    }
}
