//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DormAllocation
    {
        public int ID { get; set; }
        public int ReferenceNumberId { get; set; }
        public Nullable<int> FactoryCodeId { get; set; }
        public string OfficeName { get; set; }
        public Nullable<int> BookingDetailsIDId { get; set; }
        public Nullable<int> DormNumberId { get; set; }
        public Nullable<int> CheckinStaffId { get; set; }
        public Nullable<System.DateTime> dbedited { get; set; }
        public System.DateTime Modified { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
