//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormData
{
    using System;
    using System.Collections.Generic;
    
    public partial class maintenancing
    {
        public System.DateTime mtdate { get; set; }
        public string DormCode { get; set; }
        public System.DateTime dbedited { get; set; }
    }
}
