//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyList
    {
        public int ID { get; set; }
        public System.DateTime Modified { get; set; }
        public string OData__x0079_jb6 { get; set; }
        public string Title { get; set; }
        public string shgk { get; set; }
        public Nullable<System.DateTime> dbedited { get; set; }
    }
}
