//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormData
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatisticsByDay
    {
        public System.DateTime start { get; set; }
        public int DormCodeId { get; set; }
        public int guestnum { get; set; }
        public int roomnum { get; set; }
        public Nullable<int> maintenance { get; set; }
        public System.DateTime edittime { get; set; }
    }
}
